-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 23:15:41 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema examen_2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema examen_2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `examen_2` DEFAULT CHARACTER SET utf8 ;
USE `examen_2` ;

-- -----------------------------------------------------
-- Table `examen_2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen_2`.`usuario` (
  `id` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examen_2`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen_2`.`producto` (
  `codigo` INT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Precio` DECIMAL NOT NULL,
  `Existencia` INT NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examen_2`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen_2`.`pedidos` (
  `id` INT NOT NULL,
  `identidadcliente` VARCHAR(45) NOT NULL,
  `Cliente` VARCHAR(45) NULL,
  `Fecha` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `examen_2`.`Descripcion pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `examen_2`.`Descripcion pedidos` (
  `id` INT NOT NULL,
  `idpedidos` INT NULL,
  `Codigoproducto` VARCHAR(45) NULL,
  `Cantidad` INT NULL,
  `Precio` DECIMAL NULL,
  `Total` DECIMAL NULL,
  `Descripcion pedidoscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `Fk_Descripcion pedidos_pedidos_idx` (`idpedidos` ASC) VISIBLE,
  CONSTRAINT `FK_Descripcion pedidos_producto`
    FOREIGN KEY (`id`)
    REFERENCES `examen_2`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_Descripcion pedidos_pedidos`
    FOREIGN KEY (`idpedidos`)
    REFERENCES `examen_2`.`pedidos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
